### ISSUE TITLE
blank screen when accessing maiden using Edge browser

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#157]
As reported on lines:
https://llllllll.co/t/norns-2-0-1/21721/73

It was in Edge that I had problems connecting to maiden. No problem in Chrome.

Error message is below:

Endpoints: [object Map]

Units: [object Map]

Error during service worker registration: SecurityError

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier). (Fetch)GET - http://192.168.1.203/api/v1/dust/data/editor.json

[object Error]: {description: “Object doesn’t support property or method ‘scrollTo’”, message: “Object doesn’t support property or method ‘scrollTo’”, number: -2146827850, stack: “TypeError: Object doesn’t support property or method ‘scrollTo’ at value (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:1243148) at mr (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:624269) at br (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:625788) at Anonymous function (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:638789) at t.unstable_runWithPriority (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:673651) at Hr (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:638676) at Wr (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:638471) at zr (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:637843) at $r (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:636621) at Fr (http://192.168.1.203/maiden/static/js/main.147e1296.js:1:635768)”}

0: Object doesn’t support property or method ‘scrollTo’

main.147e1296.js (1,638023)

**Comment by ngwese** [comment]
the initial impression is that it is the call to the `scrollTo` method which is likely causing the rendering to fail. to the best of my memory the only place `scrollTo` is being used is in the REPL as it tries to keep the newest REPL output (added to the bottom of the containing DIV) visible.
